import { useEffect, useState } from "react";
import { api } from "../api.js";
import { SkeletonTable } from "../components/Skeleton.jsx";
import { useToast } from "../components/Toast.jsx";

export default function Invoices() {
  const { addToast } = useToast();
  const [text, setText] = useState("");
  const [result, setResult] = useState(null);
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(false);
  const [listLoading, setListLoading] = useState(true);
  const [error, setError] = useState("");

  async function loadInvoices() {
    try {
      setListLoading(true);
      const res = await api.getInvoices();
      setRows(res || []);
    } catch (err) {
      console.error(err);
    } finally {
      setListLoading(false);
    }
  }

  useEffect(() => {
    loadInvoices();
  }, []);

  async function handleSubmit(e) {
    e.preventDefault();
    if (!text.trim()) return;

    setLoading(true);
    setError("");

    try {
      const res = await api.generateInvoice(text.trim());
      setResult(res.data);
      setText("");
      addToast("Invoice generated successfully");
      await loadInvoices();
    } catch (err) {
      console.error(err);
      setError(err.message);
      addToast(err.message, "error");
    } finally {
      setLoading(false);
    }
  }

  function handleDownload(invoice) {
    const printWindow = window.open('', '_blank');
    const content = `
      <html>
        <head>
          <title>Invoice ${invoice.invoice_number}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #333; }
            .header { display: flex; justify-content: space-between; border-bottom: 2px solid #6366f1; padding-bottom: 20px; }
            .brand { color: #6366f1; font-size: 24px; font-weight: bold; }
            .invoice-info { text-align: right; }
            .details { margin-top: 40px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { text-align: left; background: #f8fafc; padding: 12px; border-bottom: 1px solid #e2e8f0; }
            td { padding: 12px; border-bottom: 1px solid #e2e8f0; }
            .total-row { font-weight: bold; font-size: 18px; }
            .footer { margin-top: 60px; font-size: 12px; color: #64748b; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="brand">LedgerLink</div>
            <div class="invoice-info">
              <div>Invoice #: ${invoice.invoice_number}</div>
              <div>Date: ${new Date().toLocaleDateString()}</div>
            </div>
          </div>
          <div class="details">
            <h3>Invoice Summary</h3>
            <table>
              <thead>
                <tr>
                  <th>Description</th>
                  <th>Amount</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Professional Services</td>
                  <td>${invoice.currency} ${invoice.amount ?? invoice.total}</td>
                </tr>
                <tr class="total-row">
                  <td>Total</td>
                  <td>${invoice.currency} ${invoice.amount ?? invoice.total}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="footer">
            Thank you for your business! Generated by LedgerLink AI.
          </div>
          <script>
            window.onload = function() { window.print(); window.close(); }
          </script>
        </body>
      </html>
    `;
    printWindow.document.write(content);
    printWindow.document.close();
  }

  async function toggleStatus(invoice) {
    const nextStatus = invoice.status === "Paid" ? "Pending" : "Paid";
    try {
      await api.updateInvoiceStatus(invoice.id, nextStatus);
      addToast(`Invoice status updated to ${nextStatus}`);
      await loadInvoices();
    } catch (err) {
      console.error(err);
    }
  }

  return (
    <div>
      <h3>Invoices</h3>
      <p className="muted">
        Describe the work and amount, e.g. “Create invoice for web development
        for Acme Corp 50000”.
      </p>

      <form onSubmit={handleSubmit} className="card form">
        <label>Invoice request</label>
        <textarea
          rows={3}
          value={text}
          onChange={(e) => setText(e.target.value)}
        />
        <button type="submit" disabled={loading}>
          {loading ? "Generating..." : "Generate & Save"}
        </button>
        {error && <div className="error">{error}</div>}
      </form>

      {result && (
        <div className="card" style={{ marginTop: "1rem" }}>
          <h4>Last Invoice</h4>
          <div className="prediction">
            <div>
              <div className="pill">Invoice #</div>
              <div className="prediction-main">{result.invoice_number}</div>
            </div>
            <div>
              <div>Amount: {result.total ?? result.amount ?? "—"}</div>
              <div>Currency: {result.currency || "INR"}</div>
              <div>
                Due date: {(result.due_date || "").toString().slice(0, 10)}
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="card" style={{ marginTop: "1.5rem" }}>
        <h4>Stored Invoices</h4>
        {listLoading ? (
          <SkeletonTable rows={5} cols={5} />
        ) : (
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Invoice #</th>
                  <th>Amount</th>
                  <th>Due</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.id}>
                    <td>{r.id}</td>
                    <td style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <span 
                        onClick={() => toggleStatus(r)}
                        style={{ 
                          cursor: 'pointer',
                          display: 'inline-flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          width: '20px',
                          height: '20px',
                          borderRadius: '50%',
                          fontSize: '12px',
                          fontWeight: 'bold',
                          background: r.status === 'Paid' ? '#10b981' : '#f59e0b',
                          color: 'white'
                        }}
                        title={r.status === 'Paid' ? 'Paid' : 'Pending'}
                      >
                        P
                      </span>
                      {r.invoice_number}
                    </td>
                    <td>{r.amount ?? r.total}</td>
                    <td>{(r.due || r.due_date || "").slice(0, 10)}</td>
                    <td>
                      <div style={{ display: 'flex', gap: '5px' }}>
                        <button 
                          className="btn-small" 
                          onClick={() => handleDownload(r)}
                          style={{ padding: '4px 10px', fontSize: '0.75rem' }}
                        >
                          PDF
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}

                {rows.length === 0 && (
                  <tr>
                    <td colSpan="5" className="muted">
                      No invoices yet.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}