import { useEffect, useState, useRef } from "react";
import { api } from "../api.js";
import { SkeletonTable } from "../components/Skeleton.jsx";
import { useToast } from "../components/Toast.jsx";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

export default function Invoices() {
  const { addToast } = useToast();
  const [text, setText] = useState("");
  const [result, setResult] = useState(null);
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(false);
  const [listLoading, setListLoading] = useState(true);
  const [error, setError] = useState("");
  const invoicePreviewRef = useRef(null);

  async function loadInvoices() {
    try {
      setListLoading(true);
      const res = await api.getInvoices();
      setRows(res || []);
    } catch (err) {
      console.error(err);
    } finally {
      setListLoading(false);
    }
  }

  useEffect(() => {
    loadInvoices();
  }, []);

  async function handleSubmit(e) {
    e.preventDefault();
    if (!text.trim()) return;

    setLoading(true);
    setError("");

    try {
      const res = await api.generateInvoice(text.trim());
      setResult(res.data);
      setText("");
      addToast("Invoice generated successfully");
      await loadInvoices();
    } catch (err) {
      console.error(err);
      setError(err.message);
      addToast(err.message, "error");
    } finally {
      setLoading(false);
    }
  }

  async function handleDownload(invoice) {
    try {
      // Create a temporary div for PDF generation
      const tempDiv = document.createElement('div');
      tempDiv.innerHTML = `
        <div style="font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #333;">
          <div style="display: flex; justify-content: space-between; border-bottom: 2px solid #6366f1; padding-bottom: 20px;">
            <div style="color: #6366f1; font-size: 28px; font-weight: bold;">LedgerLink</div>
            <div style="text-align: right;">
              <div style="font-size: 1.2rem; font-weight: bold;">Invoice #${invoice.invoice_number}</div>
              <div style="font-size: 0.95rem; color: #64748b;">Date: ${new Date().toLocaleDateString()}</div>
            </div>
          </div>
          <div style="margin-top: 60px; text-align: left;">
            <h3 style="color: #1e293b; margin-bottom: 20px;">Invoice Summary</h3>
            <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
              <thead>
                <tr style="background: #f1f5f9;">
                  <th style="text-align: left; padding: 12px; border-bottom: 1px solid #e2e8f0;">Description</th>
                  <th style="text-align: right; padding: 12px; border-bottom: 1px solid #e2e8f0;">Amount</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">Professional Services</td>
                  <td style="padding: 12px; border-bottom: 1px solid #e2e8f0; text-align: right;">${invoice.currency} ${invoice.amount ?? invoice.total}</td>
                </tr>
                <tr style="font-weight: bold; font-size: 1.1rem;">
                  <td style="text-align: right; padding: 12px; border-bottom: 2px solid #6366f1;">Total</td>
                  <td style="text-align: right; padding: 12px; border-bottom: 2px solid #6366f1;">${invoice.currency} ${invoice.amount ?? invoice.total}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div style="margin-top: 100px; text-align: center; color: #64748b; font-size: 0.85rem;">
            Thank you for your business! Generated by LedgerLink AI.
          </div>
        </div>
      `;
      document.body.appendChild(tempDiv);

      // Convert to canvas
      const canvas = await html2canvas(tempDiv, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#ffffff"
      });

      // Remove temporary div
      document.body.removeChild(tempDiv);

      // Create PDF
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgWidth = 210;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
      pdf.save(`Invoice-${invoice.invoice_number}.pdf`);
      addToast("PDF downloaded successfully!");
    } catch (err) {
      console.error(err);
      addToast("Failed to download PDF", "error");
    }
  }

  async function toggleStatus(invoice) {
    const nextStatus = invoice.status === "Paid" ? "Pending" : "Paid";
    try {
      await api.updateInvoiceStatus(invoice.id, nextStatus);
      addToast(`Invoice status updated to ${nextStatus}`);
      await loadInvoices();
    } catch (err) {
      console.error(err);
    }
  }

  return (
    <div>
      <h3>Invoices</h3>
      <p className="muted">
        Describe the work and amount, e.g. “Create invoice for web development
        for Acme Corp 50000”.
      </p>

      <form onSubmit={handleSubmit} className="card form">
        <label>Invoice request</label>
        <textarea
          rows={3}
          value={text}
          onChange={(e) => setText(e.target.value)}
        />
        <button type="submit" disabled={loading}>
          {loading ? "Generating..." : "Generate & Save"}
        </button>
        {error && <div className="error">{error}</div>}
      </form>

      {result && (
        <div className="card" style={{ marginTop: "1rem" }}>
          <h4>Last Invoice</h4>
          <div className="prediction">
            <div>
              <div className="pill">Invoice #</div>
              <div className="prediction-main">{result.invoice_number}</div>
            </div>
            <div>
              <div>Amount: {result.total ?? result.amount ?? "—"}</div>
              <div>Currency: {result.currency || "INR"}</div>
              <div>
                Due date: {(result.due_date || "").toString().slice(0, 10)}
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="card" style={{ marginTop: "1.5rem" }}>
        <h4>Stored Invoices</h4>
        {listLoading ? (
          <SkeletonTable rows={5} cols={5} />
        ) : (
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Invoice #</th>
                  <th>Amount</th>
                  <th>Due</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.id}>
                    <td>{r.id}</td>
                    <td style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <span 
                        onClick={() => toggleStatus(r)}
                        style={{ 
                          cursor: 'pointer',
                          display: 'inline-flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          width: '20px',
                          height: '20px',
                          borderRadius: '50%',
                          fontSize: '12px',
                          fontWeight: 'bold',
                          background: r.status === 'Paid' ? '#10b981' : '#f59e0b',
                          color: 'white'
                        }}
                        title={r.status === 'Paid' ? 'Paid' : 'Pending'}
                      >
                        P
                      </span>
                      {r.invoice_number}
                    </td>
                    <td>{r.amount ?? r.total}</td>
                    <td>{(r.due || r.due_date || "").slice(0, 10)}</td>
                    <td>
                      <div style={{ display: 'flex', gap: '5px' }}>
                        <button 
                          className="btn-small" 
                          onClick={() => handleDownload(r)}
                          style={{ padding: '4px 10px', fontSize: '0.75rem' }}
                        >
                          PDF
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}

                {rows.length === 0 && (
                  <tr>
                    <td colSpan="5" className="muted">
                      No invoices yet.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}